# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Letzgo' do

  # Pods for Letzgo
  pod 'RestKit', '~> 0.24.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'MBProgressHUD'
  pod 'AWSCore'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'Toast', '~> 3.1.0'
  pod 'SCLAlertView-Objective-C'
  pod 'EMCCountryPickerController', '~> 1.0'
  pod 'Stripe'
  pod 'NSObject-ObjectMap', '~> 2.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'UIImage-Categories'
  pod 'SDWebImage', '~>3.7'
  pod 'UIAlertController+Blocks'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'HCSStarRatingView', '~> 1.4.5'
  pod 'AppsFlyerFramework'
  #pod 'GoogleMaps/M4B'
end
